expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView


urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
            model=Expense,
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-create'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
            model=Category,
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_delete.html'
         ),
         name='category-delete'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

expenses/forms.py
from cProfile import label

from django import forms
from .models import Expense, Category


class ExpenseSearchForm(forms.ModelForm):
    DROPDOWN_LIST = [
        ('date_up', 'Date Up'),
        ('date_down', 'Date Down'),
        ('category_up', 'Category Up'),
        ('category_down', 'Category Down'),
    ]

    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple,
                                              required=False)
    search_from_date = forms.DateField(widget=forms.SelectDateWidget(years=range(2020, 2024)), required=False)
    search_to_date = forms.DateField(widget=forms.SelectDateWidget(years=range(2020, 2024)), required=False)

    sorting = forms.CharField(label='Choose the sorting', widget=forms.Select(choices=DROPDOWN_LIST))


    class Meta:
        model = Expense
        fields = ['name',  ]

        widgets = {'category': forms.CheckboxSelectMultiple,}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False


class CategorySearchForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['name',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False

expenses/views.py
from django.views.generic.list import ListView
from .forms import ExpenseSearchForm
from .models import Expense, Category
from .reports import summary_per_category, summary_per_year, summary_per_month, total_amount, number_expenses_per_category


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list

        form = ExpenseSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()

            from_date = form.cleaned_data.get('search_from_date')
            to_date = form.cleaned_data.get('search_to_date')
            category = form.cleaned_data.get('category')
            sorting = form.cleaned_data.get('sorting')

            if name:
                queryset = queryset.filter(name__icontains=name)
            if from_date:
                queryset = queryset.filter(date__gte=from_date).order_by('-date')
            if to_date:
                queryset = queryset.filter(date__lte=to_date).order_by('-date')

            if category:
                category_first = queryset.filter(category__name=category[0])
                for el in category:
                    category_el = queryset.filter(category__name=el)
                    category_first = category_first | category_el
                queryset = category_first

            if sorting:
                if sorting == 'category_up':
                    queryset = queryset.order_by('category')
                elif sorting == 'category_down':
                    queryset = queryset.order_by('-category')
                elif sorting == 'date_down':
                    queryset = queryset.order_by('-date')
                else:
                    queryset = queryset.order_by('date')

        return super().get_context_data(
            form=form,
            object_list=queryset,
            summary_per_category=summary_per_category(queryset),
            summary_per_month=summary_per_month(queryset),
            summary_per_year=summary_per_year(queryset),
            total_amount=total_amount(queryset),
            number_expenses_per_category=number_expenses_per_category(queryset),
            **kwargs)


class CategoryListView(ListView):
    model = Category
    paginate_by = 5

expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'expenses:category-create' %}">add</a>

<table border="1">
	<thead>
		<tr>
			<th>name</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		{% for obj in object_list %}
		<tr>
			<td>
				{{obj.name}}
			</td>
			<td>
				<a href="{% url 'expenses:category-delete' obj.id %}">delete</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'expenses:expense-create' %}">add</a>

<form method="get" action="">

  {{form.as_p}}

  <button type="submit">search</button>
</form>
<br>

<table border="1">
	<caption>Expenses</caption>
	<thead>
	  <tr>
		<th>no.</th>
		<th>category</th>
		<th>name</th>
		<th>amount</th>
		<th>date</th>
		<th>total</th>
		<th>actions</th>
	  </tr>
	</thead>
	<tbody>

	{% for obj in object_list %}
	  <tr>
		<td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
		<td>{{ obj.category|default:"-" }}</td>
		<td>{{ obj.name|default:"-" }}</td>
		<td>{{ obj.amount|floatformat:2 }}</td>
		<td>{{obj.date}}</td>
		<td>{{ obj.total|floatformat:2 }}</td>
		<td>
		  <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
		  <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
		</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>

</table>
	<p> <strong> Total amount: {{ total_amount|floatformat:2}}</strong></p>



{% include "_pagination.html" %}
<hr>
<br>


<table border="1">
  <caption>Summary and number of expenses per category</caption>
	<thead>
	  <tr>

		<th>Category</th>

		<th>Summary</th>

		<th>Number of expenses</th>

	  </tr>
	</thead>
  <tr>
    {% for category, total in summary_per_category.items %}
	<tr>
		<td>{{category}}:</td>
		<td width="40%">{{total|floatformat:2}}</td>
	{% for cat, num in number_expenses_per_category.items %}
	{% if cat == category %}
		<td width="40%">{{ num }}</td>
	{% endif %}
	{% endfor %}
	</tr>
	{% endfor %}
  </tr>
</table>
<br>

<br>
<table border="1">
  <caption>Summary per year-month</caption>
  <tr>
    {% for year, total in summary_per_year.items %}
	<tr>
		<td>{{year}}:</td>
		<td width="50%">{{total|floatformat:2}}</td>
	{% endfor %}
	</tr>
  </tr>
</table>
<br>
<table border="1">
  <caption>Summary per month</caption>
  <tr>
    {% for month, total in summary_per_month.items %}
	<tr>
		<td>{{month}}:</td>
		<td width="50%">{{total|floatformat:2}}</td>
	{% endfor %}
	</tr>
  </tr>
</table>
{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> | 
	<a href="{% url 'expenses:category-list' %}">Categories</a> | 
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}